## This file is a general .xdc for the ALINX AX7010 board
## To use it in a project:
## - uncomment the lines corresponding to used pins
## - rename the used signals according to the project

##LCD Interface J10
#set_property PACKAGE_PIN W19 [get_ports {lcd_int}]
set_property PACKAGE_PIN W18 [get_ports {lcd_bl_pwm}]
#set_property PACKAGE_PIN R14 [get_ports {lcd_scl}]
#set_property PACKAGE_PIN P14 [get_ports {lcd_sda}]
set_property PACKAGE_PIN Y17 [get_ports {lcd_hsync}]
set_property PACKAGE_PIN Y16 [get_ports {lcd_vsync}]
set_property PACKAGE_PIN W15 [get_ports {lcd_dclk}]
set_property PACKAGE_PIN V15 [get_ports {lcd_de}]
set_property PACKAGE_PIN Y14 [get_ports {lcd_b[6]}]
set_property PACKAGE_PIN W14 [get_ports {lcd_b[7]}]
set_property PACKAGE_PIN P18 [get_ports {lcd_b[4]}]
set_property PACKAGE_PIN N17 [get_ports {lcd_b[5]}]
set_property PACKAGE_PIN U15 [get_ports {lcd_b[2]}]
set_property PACKAGE_PIN U14 [get_ports {lcd_b[3]}]
set_property PACKAGE_PIN P16 [get_ports {lcd_b[0]}]
set_property PACKAGE_PIN P15 [get_ports {lcd_b[1]}]
set_property PACKAGE_PIN U17 [get_ports {lcd_g[6]}]
set_property PACKAGE_PIN T16 [get_ports {lcd_g[7]}]
set_property PACKAGE_PIN V18 [get_ports {lcd_g[4]}]
set_property PACKAGE_PIN V17 [get_ports {lcd_g[5]}]
set_property PACKAGE_PIN T15 [get_ports {lcd_g[2]}]
set_property PACKAGE_PIN T14 [get_ports {lcd_g[3]}]
set_property PACKAGE_PIN V13 [get_ports {lcd_g[0]}]
set_property PACKAGE_PIN U13 [get_ports {lcd_g[1]}]
set_property PACKAGE_PIN W13 [get_ports {lcd_r[6]}]
set_property PACKAGE_PIN V12 [get_ports {lcd_r[7]}]
set_property PACKAGE_PIN U12 [get_ports {lcd_r[4]}]
set_property PACKAGE_PIN T12 [get_ports {lcd_r[5]}]
set_property PACKAGE_PIN T10 [get_ports {lcd_r[2]}]
set_property PACKAGE_PIN T11 [get_ports {lcd_r[3]}]
set_property PACKAGE_PIN A20 [get_ports {lcd_r[0]}]
set_property PACKAGE_PIN B19 [get_ports {lcd_r[1]}]

#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_int}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_bl_pwm}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_scl}]
#set_property IOSTANDARD LVCMOS33 [get_ports {lcd_sda}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_hsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_vsync}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_dclk}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_de}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_r[1]}]


