set_property IOSTANDARD LVCMOS33 [get_ports {led_4b_tri_o[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4b_tri_o[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4b_tri_o[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_4b_tri_o[0]}]
set_property PACKAGE_PIN M14 [get_ports {led_4b_tri_o[0]}]
set_property PACKAGE_PIN M15 [get_ports {led_4b_tri_o[1]}]
set_property PACKAGE_PIN K16 [get_ports {led_4b_tri_o[2]}]
set_property PACKAGE_PIN J16 [get_ports {led_4b_tri_o[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {iic_scl_io}]
set_property PACKAGE_PIN T19 [get_ports {iic_scl_io}]
set_property IOSTANDARD LVCMOS33 [get_ports {iic_sda_io}]
set_property PACKAGE_PIN U19 [get_ports {iic_sda_io}]
