# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf.xci
# IP: The module: 'adc_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf/adc_buf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_buf'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf/adc_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf.xci
# IP: The module: 'adc_buf' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf/adc_buf_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf/adc_buf.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/test/ad7606_test_v2/axi_adc/src/adc_buf/adc_buf_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'adc_buf'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
