webtalk_init -webtalk_dir Y:\\project\\AX\\AX7020\\AX7020_CD\\02_source\\vivado_project\\04_pl_led\\pl_led.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "ÐÇÆÚÁù ¶þÔÂ 25 11:27:25 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "h4qibb9c71a6ed7nj0pv2elrss" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.4_58" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "58" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1487989704016" -context "sdk\\\\hardware/1487989704016"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1487989704016"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1487989704016"
webtalk_add_data -client sdk -key VivadoVersion -value "2015.4" -context "sdk\\\\hardware/1487989704016"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1487989704016"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1487989704016"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1487989704016"
webtalk_transmit -clientid 2623717442 -regid "" -xml Y:\\project\\AX\\AX7020\\AX7020_CD\\02_source\\vivado_project\\04_pl_led\\pl_led.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html Y:\\project\\AX\\AX7020\\AX7020_CD\\02_source\\vivado_project\\04_pl_led\\pl_led.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm Y:\\project\\AX\\AX7020\\AX7020_CD\\02_source\\vivado_project\\04_pl_led\\pl_led.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
